/* ============================================================
   GAAWOW EMS
   STUDENTS MANAGEMENT
   JavaScript V5.5
   ============================================================

   IMPORTANT:
   - Student ID is generated by Supabase/database trigger.
   - JS NEVER generates or updates student_id.
   - Expected format:
       GA-2026-000001
       GA-2026-000002
       GA-2026-000003
       ...
   - Existing IDs are preserved.
   - Super Admin only.
   ============================================================ */


/* ============================================================
   1. SUPABASE CONFIGURATION
   ============================================================ */

/*
   Haddii Supabase client hore meel kale looga sameeyay,
   code-kan wuxuu isku dayayaa inuu isticmaalo.

   Haddii kale, geli URL iyo ANON KEY-gaaga.
*/

const SUPABASE_URL =
  window.GAAWOW_SUPABASE_URL ||
  "YOUR_SUPABASE_URL";

const SUPABASE_ANON_KEY =
  window.GAAWOW_SUPABASE_ANON_KEY ||
  "YOUR_SUPABASE_ANON_KEY";


let supabaseClient = null;


try {

  if (
    window.supabase &&
    SUPABASE_URL !== "YOUR_SUPABASE_URL" &&
    SUPABASE_ANON_KEY !== "YOUR_SUPABASE_ANON_KEY"
  ) {

    supabaseClient =
      window.supabase.createClient(
        SUPABASE_URL,
        SUPABASE_ANON_KEY
      );

  }

} catch (error) {

  console.error(
    "Supabase initialization error:",
    error
  );

}



/* ============================================================
   2. GLOBAL STATE
   ============================================================ */

let students = [];

let institutions = [];

let filteredStudents = [];

let editingStudent = null;

let currentPhotoUrl = "";

let isSaving = false;

let currentUser = null;

let currentProfile = null;



/* ============================================================
   3. DOM HELPERS
   ============================================================ */

const $ = (id) =>
  document.getElementById(id);



/* ============================================================
   4. ELEMENTS
   ============================================================ */

const messageEl =
  $("message");

const studentForm =
  $("studentForm");

const institutionSelect =
  $("institutionSelect");

const studentIdInput =
  $("studentId");

const fullNameInput =
  $("fullName");

const genderInput =
  $("gender");

const dateOfBirthInput =
  $("dateOfBirth");

const phoneInput =
  $("phone");

const emailInput =
  $("email");

const admissionDateInput =
  $("admissionDate");

const statusInput =
  $("status");

const addressInput =
  $("address");

const photoInput =
  $("photoInput");

const photoPreview =
  $("photoPreview");

const photoPlaceholder =
  $("photoPlaceholder");

const editStudentDbId =
  $("editStudentDbId");

const formTitle =
  $("formTitle");

const saveButton =
  $("saveButton");

const resetFormButton =
  $("resetFormButton");

const addStudentButton =
  $("addStudentButton");

const refreshStudentsButton =
  $("refreshStudentsButton");

const searchInput =
  $("searchInput");

const statusFilter =
  $("statusFilter");

const studentsTableBody =
  $("studentsTableBody");

const totalStudentsEl =
  $("totalStudents");

const activeStudentsEl =
  $("activeStudents");

const graduatedStudentsEl =
  $("graduatedStudents");

const otherStudentsEl =
  $("otherStudents");

const progressWrap =
  $("progressWrap");

const progressBar =
  $("progressBar");

const progressText =
  $("progressText");

const accountStatus =
  $("accountStatus");

const createAccountButton =
  $("createAccountButton");

const resetPasswordButton =
  $("resetPasswordButton");

const profileModal =
  $("profileModal");

const profileContent =
  $("profileContent");

const closeProfileModal =
  $("closeProfileModal");



/* ============================================================
   5. MESSAGE SYSTEM
   ============================================================ */

function showMessage(
  text,
  type = "success"
) {

  if (!messageEl) {
    return;
  }

  messageEl.textContent =
    text;

  messageEl.className =
    "message " + type;

  messageEl.style.display =
    "block";

  window.scrollTo({
    top: 0,
    behavior: "smooth"
  });

}


function hideMessage() {

  if (!messageEl) {
    return;
  }

  messageEl.textContent =
    "";

  messageEl.className =
    "message";

  messageEl.style.display =
    "none";

}



/* ============================================================
   6. PROGRESS
   ============================================================ */

function showProgress(
  percent = 0,
  text = ""
) {

  if (!progressWrap) {
    return;
  }

  progressWrap.style.display =
    "block";

  progressBar.style.width =
    `${percent}%`;

  progressText.textContent =
    text;
}


function hideProgress() {

  if (!progressWrap) {
    return;
  }

  progressWrap.style.display =
    "none";

  progressBar.style.width =
    "0%";

  progressText.textContent =
    "";
}



/* ============================================================
   7. SUPABASE CHECK
   ============================================================ */

function ensureSupabase() {

  if (!supabaseClient) {

    throw new Error(
      "Supabase lama xiriirin. Fadlan geli SUPABASE_URL iyo SUPABASE_ANON_KEY."
    );

  }

}



/* ============================================================
   8. AUTH USER
   ============================================================ */

async function getCurrentUser() {

  ensureSupabase();

  const {
    data,
    error
  } =
    await supabaseClient.auth.getUser();

  if (error) {
    throw error;
  }

  if (!data?.user) {

    throw new Error(
      "User-ka lama helin. Fadlan login samee."
    );

  }

  currentUser =
    data.user;

  return currentUser;
}



/* ============================================================
   9. SUPER ADMIN CHECK
   ============================================================ */

async function checkSuperAdmin() {

  ensureSupabase();

  const user =
    await getCurrentUser();


  /*
     Waxaan isku dayeynaa profiles table.
  */

  const {
    data,
    error
  } =
    await supabaseClient
      .from("profiles")
      .select(
        "id,role,full_name,email"
      )
      .eq(
        "id",
        user.id
      )
      .maybeSingle();


  if (error) {

    console.warn(
      "Profile role check failed:",
      error
    );

    /*
      RLS / database policy ayaa sidoo kale
      ilaalinaysa system-ka.
    */

    return true;
  }


  currentProfile =
    data;


  const role =
    String(
      data?.role || ""
    ).toLowerCase();


  const isSuperAdmin =
    [
      "super_admin",
      "super admin",
      "superadmin"
    ].includes(role);


  if (!isSuperAdmin) {

    throw new Error(
      "Access denied. Super Admin oo keliya ayaa maamuli kara Students."
    );

  }

  return true;
}



/* ============================================================
   10. LOAD INSTITUTIONS
   ============================================================ */

async function loadInstitutions() {

  ensureSupabase();


  if (!institutionSelect) {
    return;
  }


  institutionSelect.innerHTML =
    `
      <option value="">
        Loading institutions...
      </option>
    `;


  const {
    data,
    error
  } =
    await supabaseClient
      .from("institutions")
      .select(
        "*"
      )
      .order(
        "name",
        {
          ascending: true
        }
      );


  if (error) {

    console.error(
      "Institution loading error:",
      error
    );

    institutionSelect.innerHTML =
      `
        <option value="">
          Unable to load institutions
        </option>
      `;

    throw error;
  }


  institutions =
    data || [];


  institutionSelect.innerHTML =
    `
      <option value="">
        Select institution
      </option>
    `;


  institutions.forEach(
    institution => {

      const option =
        document.createElement(
          "option"
        );

      option.value =
        institution.id;

      option.textContent =
        institution.name ||
        institution.institution_name ||
        "Unnamed Institution";

      institutionSelect.appendChild(
        option
      );

    }
  );

}



/* ============================================================
   11. DATE HELPERS
   ============================================================ */

function formatDate(
  value
) {

  if (!value) {
    return "—";
  }

  try {

    const date =
      new Date(
        value
      );

    if (
      Number.isNaN(
        date.getTime()
      )
    ) {
      return value;
    }

    return date.toLocaleDateString(
      "en-GB",
      {
        year: "numeric",
        month: "short",
        day: "2-digit"
      }
    );

  } catch {
    return value;
  }
}



function dateForInput(
  value
) {

  if (!value) {
    return "";
  }

  return String(
    value
  ).slice(
    0,
    10
  );
}



/* ============================================================
   12. ESCAPE HTML
   ============================================================ */

function escapeHtml(
  value
) {

  if (
    value === null ||
    value === undefined
  ) {
    return "";
  }

  return String(
    value
  )
    .replace(
      /&/g,
      "&amp;"
    )
    .replace(
      /</g,
      "&lt;"
    )
    .replace(
      />/g,
      "&gt;"
    )
    .replace(
      /"/g,
      "&quot;"
    )
    .replace(
      /'/g,
      "&#039;"
    );
}



/* ============================================================
   13. STATUS BADGE
   ============================================================ */

function statusBadge(
  status
) {

  const normalized =
    String(
      status || ""
    ).toLowerCase();


  let className =
    "status-inactive";


  let label =
    "Inactive";


  if (
    normalized === "active"
  ) {

    className =
      "status-active";

    label =
      "Active";

  }
  else if (
    normalized === "graduated"
  ) {

    className =
      "status-graduated";

    label =
      "Graduated";

  }
  else if (
    normalized === "suspended"
  ) {

    className =
      "status-suspended";

    label =
      "Suspended";

  }


  return `
    <span class="status ${className}">
      ${escapeHtml(label)}
    </span>
  `;
}



/* ============================================================
   14. ACCOUNT STATUS
   ============================================================ */

function getAccountState(
  student
) {

  if (
    student?.account_enabled === true &&
    student?.auth_user_id
  ) {

    return {
      label: "Active",
      className: "status-active"
    };

  }


  if (
    student?.auth_user_id &&
    student?.account_enabled === false
  ) {

    return {
      label: "Disabled",
      className: "status-suspended"
    };

  }


  return {
    label: "No Account",
    className: "status-inactive"
  };

}



function accountBadge(
  student
) {

  const state =
    getAccountState(
      student
    );


  return `
    <span class="status ${state.className}">
      ${escapeHtml(state.label)}
    </span>
  `;
}



/* ============================================================
   15. INITIALS
   ============================================================ */

function getInitials(
  name
) {

  if (!name) {
    return "?";
  }


  const parts =
    String(
      name
    )
      .trim()
      .split(
        /\s+/
      )
      .filter(Boolean);


  if (!parts.length) {
    return "?";
  }


  if (
    parts.length === 1
  ) {

    return parts[0]
      .slice(
        0,
        2
      )
      .toUpperCase();

  }


  return (
    parts[0][0] +
    parts[parts.length - 1][0]
  ).toUpperCase();

}



/* ============================================================
   16. LOAD STUDENTS
   ============================================================ */

async function loadStudents() {

  ensureSupabase();


  renderLoadingRow();


  const {
    data,
    error
  } =
    await supabaseClient
      .from("students")
      .select(
        `
          id,
          institution_id,
          auth_user_id,
          student_id,
          full_name,
          gender,
          date_of_birth,
          phone,
          email,
          address,
          photo_url,
          admission_date,
          status,
          account_enabled,
          login_username,
          account_created_at,
          last_login_at,
          password_changed_at
        `
      )
      .order(
        "created_at",
        {
          ascending: false
        }
      );


  if (error) {

    console.error(
      "Students loading error:",
      error
    );

    renderEmptyRow(
      "Unable to load students."
    );

    throw error;
  }


  students =
    data || [];


  filteredStudents =
    [...students];


  updateStatistics();

  applyFiltersAndRender();

}



/* ============================================================
   17. LOADING ROW
   ============================================================ */

function renderLoadingRow() {

  if (!studentsTableBody) {
    return;
  }

  studentsTableBody.innerHTML =
    `
      <tr>
        <td
          colspan="10"
          class="empty"
        >
          Loading students...
        </td>
      </tr>
    `;
}



function renderEmptyRow(
  message = "No students found."
) {

  if (!studentsTableBody) {
    return;
  }

  studentsTableBody.innerHTML =
    `
      <tr>
        <td
          colspan="10"
          class="empty"
        >
          ${escapeHtml(message)}
        </td>
      </tr>
    `;
}



/* ============================================================
   18. STATISTICS
   ============================================================ */

function updateStatistics() {

  const total =
    students.length;


  const active =
    students.filter(
      student =>
        String(
          student.status
        ).toLowerCase() === "active"
    ).length;


  const graduated =
    students.filter(
      student =>
        String(
          student.status
        ).toLowerCase() === "graduated"
    ).length;


  const other =
    total -
    active -
    graduated;


  if (totalStudentsEl) {
    totalStudentsEl.textContent =
      total;
  }

  if (activeStudentsEl) {
    activeStudentsEl.textContent =
      active;
  }

  if (graduatedStudentsEl) {
    graduatedStudentsEl.textContent =
      graduated;
  }

  if (otherStudentsEl) {
    otherStudentsEl.textContent =
      other;
  }

}



/* ============================================================
   19. FILTER
   ============================================================ */

function applyFiltersAndRender() {

  const search =
    String(
      searchInput?.value || ""
    )
      .trim()
      .toLowerCase();


  const selectedStatus =
    String(
      statusFilter?.value || ""
    )
      .trim()
      .toLowerCase();


  filteredStudents =
    students.filter(
      student => {

        const searchableText =
          [
            student.student_id,
            student.full_name,
            student.phone,
            student.email,
            student.gender,
            student.login_username
          ]
            .filter(Boolean)
            .join(" ")
            .toLowerCase();


        const matchesSearch =
          !search ||
          searchableText.includes(
            search
          );


        const matchesStatus =
          !selectedStatus ||
          String(
            student.status || ""
          ).toLowerCase() ===
          selectedStatus;


        return (
          matchesSearch &&
          matchesStatus
        );

      }
    );


  renderStudents();

}



/* ============================================================
   20. RENDER STUDENTS
   ============================================================ */

function renderStudents() {

  if (!studentsTableBody) {
    return;
  }


  if (
    !filteredStudents.length
  ) {

    renderEmptyRow(
      "No students match your search."
    );

    return;
  }


  studentsTableBody.innerHTML =
    filteredStudents
      .map(
        student =>
          createStudentRow(
            student
          )
      )
      .join("");

}



/* ============================================================
   21. STUDENT ROW
   ============================================================ */

function createStudentRow(
  student
) {

  const photo =
    student.photo_url
      ? `
          <img
            src="${escapeHtml(student.photo_url)}"
            class="student-photo"
            alt="Student photo"
            loading="lazy"
            onerror="this.style.display='none'"
          >
        `
      : `
          <div
            class="initials"
            title="No photo"
          >
            ${escapeHtml(
              getInitials(
                student.full_name
              )
            )}
          </div>
        `;


  return `
    <tr>

      <td>
        ${photo}
      </td>

      <td>
        <strong>
          ${escapeHtml(
            student.student_id || "—"
          )}
        </strong>
      </td>

      <td>
        <strong>
          ${escapeHtml(
            student.full_name || "—"
          )}
        </strong>
      </td>

      <td>
        ${escapeHtml(
          student.gender || "—"
        )}
      </td>

      <td>
        ${escapeHtml(
          student.phone || "—"
        )}
      </td>

      <td>
        ${escapeHtml(
          student.email || "—"
        )}
      </td>

      <td>
        ${statusBadge(
          student.status
        )}
      </td>

      <td>
        ${escapeHtml(
          formatDate(
            student.admission_date
          )
        )}
      </td>

      <td>
        ${accountBadge(
          student
        )}
      </td>

      <td>

        <div class="actions">

          <button
            type="button"
            class="btn-small action-view"
            data-action="view"
            data-id="${escapeHtml(student.id)}"
          >
            View
          </button>

          <button
            type="button"
            class="btn-small action-edit"
            data-action="edit"
            data-id="${escapeHtml(student.id)}"
          >
            Edit
          </button>

          ${
            !student.auth_user_id
              ? `
                <button
                  type="button"
                  class="btn-small action-create-account"
                  data-action="create-account"
                  data-id="${escapeHtml(student.id)}"
                >
                  Create Account
                </button>
              `
              : `
                <button
                  type="button"
                  class="btn-small action-reset-password"
                  data-action="reset-password"
                  data-id="${escapeHtml(student.id)}"
                >
                  Reset Password
                </button>
              `
          }

          <button
            type="button"
            class="btn-small action-delete"
            data-action="delete"
            data-id="${escapeHtml(student.id)}"
          >
            Delete
          </button>

        </div>

      </td>

    </tr>
  `;
}



/* ============================================================
   22. FIND STUDENT
   ============================================================ */

function findStudentByDbId(
  dbId
) {

  return students.find(
    student =>
      String(student.id) ===
      String(dbId)
  );

}



/* ============================================================
   23. RESET FORM
   ============================================================ */

function resetStudentForm() {

  editingStudent =
    null;

  currentPhotoUrl =
    "";


  if (studentForm) {
    studentForm.reset();
  }


  if (editStudentDbId) {
    editStudentDbId.value =
      "";
  }


  if (studentIdInput) {
    studentIdInput.value =
      "";

    studentIdInput.placeholder =
      "Generated automatically";
  }


  if (statusInput) {
    statusInput.value =
      "active";
  }


  if (admissionDateInput) {

    const today =
      new Date();

    admissionDateInput.value =
      today
        .toISOString()
        .slice(
          0,
          10
        );

  }


  if (photoPreview) {

    photoPreview.src =
      "";

    photoPreview.style.display =
      "none";

  }


  if (photoPlaceholder) {

    photoPlaceholder.style.display =
      "flex";

  }


  if (photoInput) {
    photoInput.value =
      "";
  }


  if (formTitle) {
    formTitle.textContent =
      "Add Student";
  }


  if (saveButton) {
    saveButton.textContent =
      "Save Student";
  }


  if (accountStatus) {

    accountStatus.textContent =
      "No Account";

    accountStatus.className =
      "status status-inactive";

  }


  if (createAccountButton) {
    createAccountButton.style.display =
      "none";
  }


  if (resetPasswordButton) {
    resetPasswordButton.style.display =
      "none";
  }


  hideProgress();

}



/* ============================================================
   24. EDIT STUDENT
   ============================================================ */

function editStudent(
  student
) {

  if (!student) {
    return;
  }


  editingStudent =
    student;


  if (editStudentDbId) {
    editStudentDbId.value =
      student.id || "";
  }


  /*
     Student ID is READ ONLY.
     We only display it.
     We NEVER update it.
  */

  if (studentIdInput) {
    studentIdInput.value =
      student.student_id || "";
  }


  if (institutionSelect) {
    institutionSelect.value =
      student.institution_id || "";
  }


  if (fullNameInput) {
    fullNameInput.value =
      student.full_name || "";
  }


  if (genderInput) {
    genderInput.value =
      student.gender || "";
  }


  if (dateOfBirthInput) {
    dateOfBirthInput.value =
      dateForInput(
        student.date_of_birth
      );
  }


  if (phoneInput) {
    phoneInput.value =
      student.phone || "";
  }


  if (emailInput) {
    emailInput.value =
      student.email || "";
  }


  if (admissionDateInput) {
    admissionDateInput.value =
      dateForInput(
        student.admission_date
      );
  }


  if (statusInput) {
    statusInput.value =
      student.status || "active";
  }


  if (addressInput) {
    addressInput.value =
      student.address || "";
  }


  currentPhotoUrl =
    student.photo_url || "";


  if (student.photo_url) {

    photoPreview.src =
      student.photo_url;

    photoPreview.style.display =
      "block";

    photoPlaceholder.style.display =
      "none";

  }
  else {

    photoPreview.src =
      "";

    photoPreview.style.display =
      "none";

    photoPlaceholder.style.display =
      "flex";

  }


  updateAccountControls(
    student
  );


  if (formTitle) {
    formTitle.textContent =
      "Edit Student";
  }


  if (saveButton) {
    saveButton.textContent =
      "Update Student";
  }


  document
    .querySelector(
      ".card"
    )
    ?.scrollIntoView({
      behavior: "smooth",
      block: "start"
    });

}



/* ============================================================
   25. ACCOUNT CONTROLS
   ============================================================ */

function updateAccountControls(
  student
) {

  if (!student) {

    if (accountStatus) {

      accountStatus.textContent =
        "No Account";

      accountStatus.className =
        "status status-inactive";

    }

    if (createAccountButton) {
      createAccountButton.style.display =
        "none";
    }

    if (resetPasswordButton) {
      resetPasswordButton.style.display =
        "none";
    }

    return;
  }


  const state =
    getAccountState(
      student
    );


  if (accountStatus) {

    accountStatus.textContent =
      state.label;

    accountStatus.className =
      `status ${state.className}`;

  }


  if (createAccountButton) {

    createAccountButton.style.display =
      student.auth_user_id
        ? "none"
        : "inline-flex";

  }


  if (resetPasswordButton) {

    resetPasswordButton.style.display =
      student.auth_user_id
        ? "inline-flex"
        : "none";

  }

}



/* ============================================================
   26. PHOTO OPTIMIZATION
   ============================================================ */

async function optimizeImage(
  file
) {

  if (!file) {
    return null;
  }


  if (
    !file.type.startsWith(
      "image/"
    )
  ) {

    throw new Error(
      "Fadlan dooro image sax ah."
    );

  }


  if (
    file.size >
    10 * 1024 * 1024
  ) {

    throw new Error(
      "Photo-ga waa inuu ka yar yahay 10MB."
    );

  }


  const image =
    await new Promise(
      (
        resolve,
        reject
      ) => {

        const img =
          new Image();

        img.onload =
          () => resolve(img);

        img.onerror =
          () =>
            reject(
              new Error(
                "Photo lama akhrin karin."
              )
            );

        img.src =
          URL.createObjectURL(
            file
          );

      }
    );


  const maxWidth =
    900;

  const maxHeight =
    900;


  let width =
    image.width;

  let height =
    image.height;


  if (
    width > maxWidth ||
    height > maxHeight
  ) {

    const ratio =
      Math.min(
        maxWidth / width,
        maxHeight / height
      );

    width =
      Math.round(
        width * ratio
      );

    height =
      Math.round(
        height * ratio
      );

  }


  const canvas =
    document.createElement(
      "canvas"
    );


  canvas.width =
    width;

  canvas.height =
    height;


  const ctx =
    canvas.getContext(
      "2d"
    );


  ctx.drawImage(
    image,
    0,
    0,
    width,
    height
  );


  const blob =
    await new Promise(
      resolve =>
        canvas.toBlob(
          resolve,
          "image/jpeg",
          .82
        )
    );


  URL.revokeObjectURL(
    image.src
  );


  if (!blob) {

    throw new Error(
      "Photo optimization failed."
    );

  }


  return new File(
    [blob],
    `student-${Date.now()}.jpg`,
    {
      type:
        "image/jpeg"
    }
  );

}



/* ============================================================
   27. PHOTO PREVIEW
   ============================================================ */

function handlePhotoPreview(
  event
) {

  const file =
    event.target.files?.[0];


  if (!file) {
    return;
  }


  if (
    file.size >
    10 * 1024 * 1024
  ) {

    showMessage(
      "Photo-ga waa inuu ka yar yahay 10MB.",
      "error"
    );

    event.target.value =
      "";

    return;
  }


  const url =
    URL.createObjectURL(
      file
    );


  photoPreview.src =
    url;

  photoPreview.style.display =
    "block";


  photoPlaceholder.style.display =
    "none";

}



/* ============================================================
   28. UPLOAD PHOTO
   ============================================================ */

async function uploadStudentPhoto(
  file,
  studentDbId
) {

  ensureSupabase();


  const optimized =
    await optimizeImage(
      file
    );


  if (!optimized) {
    return null;
  }


  const extension =
    "jpg";


  const path =
    `students/${studentDbId}/${Date.now()}.${extension}`;


  showProgress(
    35,
    "Uploading student photo..."
  );


  /*
     Storage bucket:
       student-photos

     Haddii bucket-kaaga magaciisu ka duwan yahay,
     halkaan beddel.
  */

  const {
    error:
      uploadError
  } =
    await supabaseClient
      .storage
      .from(
        "student-photos"
      )
      .upload(
        path,
        optimized,
        {
          cacheControl:
            "3600",

          upsert:
            true,

          contentType:
            "image/jpeg"
        }
      );


  if (uploadError) {
    throw uploadError;
  }


  const {
    data:
      publicData
  } =
    supabaseClient
      .storage
      .from(
        "student-photos"
      )
      .getPublicUrl(
        path
      );


  return publicData?.publicUrl ||
    null;

}



/* ============================================================
   29. SAVE STUDENT
   ============================================================ */

async function saveStudent(
  event
) {

  event.preventDefault();


  if (isSaving) {
    return;
  }


  hideMessage();


  try {

    ensureSupabase();


    if (!fullNameInput.value.trim()) {

      showMessage(
        "Full Name waa required.",
        "error"
      );

      fullNameInput.focus();

      return;
    }


    if (
      !institutionSelect.value
    ) {

      showMessage(
        "Fadlan dooro Institution.",
        "error"
      );

      institutionSelect.focus();

      return;
    }


    if (
      !admissionDateInput.value
    ) {

      showMessage(
        "Admission Date waa required.",
        "error"
      );

      admissionDateInput.focus();

      return;
    }


    isSaving =
      true;

    saveButton.disabled =
      true;


    const isEdit =
      Boolean(
        editingStudent?.id
      );


    showProgress(
      10,
      isEdit
        ? "Updating student..."
        : "Saving student..."
    );


    /*
       IMPORTANT:
       student_id IS NOT included here.

       Database trigger generates:
       GA-2026-000001
       GA-2026-000002
       ...
    */


    const payload = {

      institution_id:
        institutionSelect.value,

      full_name:
        fullNameInput.value.trim(),

      gender:
        genderInput.value || null,

      date_of_birth:
        dateOfBirthInput.value || null,

      phone:
        phoneInput.value.trim() || null,

      email:
        emailInput.value.trim() || null,

      admission_date:
        admissionDateInput.value,

      status:
        statusInput.value,

      address:
        addressInput.value.trim() || null

    };


    let savedStudent = null;


    if (isEdit) {

      /*
         Student ID is NOT updated.
      */

      const {
        data,
        error
      } =
        await supabaseClient
          .from("students")
          .update(
            payload
          )
          .eq(
            "id",
            editingStudent.id
          )
          .select(
            `
              id,
              institution_id,
              auth_user_id,
              student_id,
              full_name,
              gender,
              date_of_birth,
              phone,
              email,
              address,
              photo_url,
              admission_date,
              status,
              account_enabled,
              login_username,
              account_created_at,
              last_login_at,
              password_changed_at
            `
          )
          .single();


      if (error) {
        throw error;
      }


      savedStudent =
        data;

    }
    else {

      const {
        data,
        error
      } =
        await supabaseClient
          .from("students")
          .insert(
            payload
          )
          .select(
            `
              id,
              institution_id,
              auth_user_id,
              student_id,
              full_name,
              gender,
              date_of_birth,
              phone,
              email,
              address,
              photo_url,
              admission_date,
              status,
              account_enabled,
              login_username,
              account_created_at,
              last_login_at,
              password_changed_at
            `
          )
          .single();


      if (error) {
        throw error;
      }


      savedStudent =
        data;

    }


    showProgress(
      60,
      "Student saved. Checking photo..."
    );


    /*
       PHOTO
    */

    const photoFile =
      photoInput?.files?.[0];


    if (photoFile) {

      const photoUrl =
        await uploadStudentPhoto(
          photoFile,
          savedStudent.id
        );


      if (photoUrl) {

        const {
          data,
          error
        } =
          await supabaseClient
            .from("students")
            .update({
              photo_url:
                photoUrl
            })
            .eq(
              "id",
              savedStudent.id
            )
            .select(
              `
                id,
                institution_id,
                auth_user_id,
                student_id,
                full_name,
                gender,
                date_of_birth,
                phone,
                email,
                address,
                photo_url,
                admission_date,
                status,
                account_enabled,
                login_username,
                account_created_at,
                last_login_at,
                password_changed_at
              `
            )
            .single();


        if (error) {
          throw error;
        }


        savedStudent =
          data;

      }

    }


    showProgress(
      100,
      "Completed."
    );


    /*
       Important:
       We show the newly generated Student ID.
    */

    showMessage(
      isEdit
        ? `Student ${savedStudent.student_id || ""} updated successfully.`
        : `Student created successfully. Student ID: ${savedStudent.student_id || "generated by database"}`,
      "success"
    );


    resetStudentForm();


    await loadStudents();


  }
  catch (error) {

    console.error(
      "Save student error:",
      error
    );


    let errorMessage =
      error?.message ||
      "Unable to save student.";


    /*
       Common Supabase duplicate error.
    */

    if (
      String(
        errorMessage
      ).toLowerCase()
        .includes(
          "duplicate"
        )
    ) {

      errorMessage =
        "Xogtan horey ayay u jirtaa. Fadlan hubi Student ID, Email ama xogta kale.";

    }


    showMessage(
      errorMessage,
      "error"
    );


  }
  finally {

    isSaving =
      false;

    saveButton.disabled =
      false;

    setTimeout(
      hideProgress,
      800
    );

  }

}



/* ============================================================
   30. VIEW STUDENT
   ============================================================ */

function viewStudent(
  student
) {

  if (!student || !profileContent) {
    return;
  }


  const photo =
    student.photo_url
      ? `
          <img
            src="${escapeHtml(student.photo_url)}"
            class="profile-photo"
            alt="Student photo"
          >
        `
      : `
          <div
            class="profile-photo"
            style="
              font-size:28px;
              font-weight:900;
              color:#173b91;
            "
          >
            ${escapeHtml(
              getInitials(
                student.full_name
              )
            )}
          </div>
        `;


  const institution =
    institutions.find(
      item =>
        String(item.id) ===
        String(student.institution_id)
    );


  profileContent.innerHTML =
    `

      <div class="profile-top">

        ${photo}

        <div>

          <div class="profile-name">
            ${escapeHtml(
              student.full_name || "—"
            )}
          </div>

          <div class="profile-id">
            ${escapeHtml(
              student.student_id || "—"
            )}
          </div>

          <div style="margin-top:8px;">
            ${statusBadge(
              student.status
            )}
            &nbsp;
            ${accountBadge(
              student
            )}
          </div>

        </div>

      </div>


      <div class="profile-grid">

        <div class="profile-item">
          <strong>
            Student ID
          </strong>
          <span>
            ${escapeHtml(
              student.student_id || "—"
            )}
          </span>
        </div>


        <div class="profile-item">
          <strong>
            Institution
          </strong>
          <span>
            ${escapeHtml(
              institution?.name ||
              institution?.institution_name ||
              "—"
            )}
          </span>
        </div>


        <div class="profile-item">
          <strong>
            Full Name
          </strong>
          <span>
            ${escapeHtml(
              student.full_name || "—"
            )}
          </span>
        </div>


        <div class="profile-item">
          <strong>
            Gender
          </strong>
          <span>
            ${escapeHtml(
              student.gender || "—"
            )}
          </span>
        </div>


        <div class="profile-item">
          <strong>
            Date of Birth
          </strong>
          <span>
            ${escapeHtml(
              formatDate(
                student.date_of_birth
              )
            )}
          </span>
        </div>


        <div class="profile-item">
          <strong>
            Phone
          </strong>
          <span>
            ${escapeHtml(
              student.phone || "—"
            )}
          </span>
        </div>


        <div class="profile-item">
          <strong>
            Email
          </strong>
          <span>
            ${escapeHtml(
              student.email || "—"
            )}
          </span>
        </div>


        <div class="profile-item">
          <strong>
            Admission Date
          </strong>
          <span>
            ${escapeHtml(
              formatDate(
                student.admission_date
              )
            )}
          </span>
        </div>


        <div class="profile-item">
          <strong>
            Login Username
          </strong>
          <span>
            ${escapeHtml(
              student.login_username || "—"
            )}
          </span>
        </div>


        <div class="profile-item">
          <strong>
            Account Created
          </strong>
          <span>
            ${escapeHtml(
              formatDate(
                student.account_created_at
              )
            )}
          </span>
        </div>


        <div class="profile-item">
          <strong>
            Last Login
          </strong>
          <span>
            ${escapeHtml(
              formatDate(
                student.last_login_at
              )
            )}
          </span>
        </div>


        <div class="profile-item">
          <strong>
            Address
          </strong>
          <span>
            ${escapeHtml(
              student.address || "—"
            )}
          </span>
        </div>

      </div>

    `;


  openProfileModal();

}



/* ============================================================
   31. PROFILE MODAL
   ============================================================ */

function openProfileModal() {

  if (!profileModal) {
    return;
  }

  profileModal.classList.add(
    "show"
  );

  profileModal.setAttribute(
    "aria-hidden",
    "false"
  );

}



function closeProfileModalFn() {

  if (!profileModal) {
    return;
  }

  profileModal.classList.remove(
    "show"
  );

  profileModal.setAttribute(
    "aria-hidden",
    "true"
  );

}



/* ============================================================
   32. DELETE STUDENT
   ============================================================ */

async function deleteStudent(
  student
) {

  if (!student) {
    return;
  }


  const confirmed =
    window.confirm(
      `Delete student ${student.student_id || ""} - ${student.full_name || ""}?\n\nThis action cannot be undone.`
    );


  if (!confirmed) {
    return;
  }


  try {

    ensureSupabase();


    /*
       Security:
       Database RLS MUST restrict this to Super Admin.
    */

    const {
      error
    } =
      await supabaseClient
        .from("students")
        .delete()
        .eq(
          "id",
          student.id
        );


    if (error) {
      throw error;
    }


    showMessage(
      `Student ${student.student_id || ""} deleted successfully.`,
      "success"
    );


    if (
      editingStudent?.id ===
      student.id
    ) {

      resetStudentForm();

    }


    await loadStudents();


  }
  catch (error) {

    console.error(
      "Delete student error:",
      error
    );


    showMessage(
      error?.message ||
      "Unable to delete student.",
      "error"
    );

  }

}



/* ============================================================
   33. CREATE ACCOUNT
   ============================================================ */

async function createStudentAccount(
  student
) {

  if (!student) {
    return;
  }


  /*
     student-account-creation.js
     ayaa ah handler-ka rasmiga ah haddii uu jiro.
  */

  if (
    typeof window.openStudentAccountModal ===
    "function"
  ) {

    window.openStudentAccountModal(
      student
    );

    return;
  }


  if (
    typeof window.createStudentAccount ===
    "function"
  ) {

    await window.createStudentAccount(
      student
    );

    return;
  }


  /*
     Haddii account creation script uusan loaded ahayn.
  */

  showMessage(
    "Student account module lama helin. Hubi student-account-creation.js inuu loaded yahay.",
    "warning"
  );

}



/* ============================================================
   34. RESET PASSWORD
   ============================================================ */

async function resetStudentPassword(
  student
) {

  if (!student) {
    return;
  }


  if (
    typeof window.resetStudentPassword ===
    "function"
  ) {

    await window.resetStudentPassword(
      student
    );

    return;
  }


  if (
    typeof window.openStudentAccountModal ===
    "function"
  ) {

    window.openStudentAccountModal(
      student,
      {
        mode: "reset"
      }
    );

    return;
  }


  showMessage(
    "Student account module lama helin. Hubi student-account-creation.js inuu loaded yahay.",
    "warning"
  );

}



/* ============================================================
   35. TABLE ACTION HANDLER
   ============================================================ */

async function handleTableAction(
  event
) {

  const button =
    event.target.closest(
      "button[data-action]"
    );


  if (!button) {
    return;
  }


  const action =
    button.dataset.action;


  const dbId =
    button.dataset.id;


  const student =
    findStudentByDbId(
      dbId
    );


  if (!student) {

    showMessage(
      "Student record lama helin.",
      "error"
    );

    return;
  }


  try {

    switch (
      action
    ) {

      case "view":

        viewStudent(
          student
        );

        break;


      case "edit":

        editStudent(
          student
        );

        break;


      case "create-account":

        await createStudentAccount(
          student
        );

        break;


      case "reset-password":

        await resetStudentPassword(
          student
        );

        break;


      case "delete":

        await deleteStudent(
          student
        );

        break;

    }

  }
  catch (error) {

    console.error(
      "Student action error:",
      error
    );

    showMessage(
      error?.message ||
      "Action failed.",
      "error"
    );

  }

}



/* ============================================================
   36. CREATE ACCOUNT BUTTON
   ============================================================ */

async function handleCreateAccountButton() {

  if (!editingStudent) {

    showMessage(
      "Marka hore dooro student.",
      "warning"
    );

    return;
  }


  await createStudentAccount(
    editingStudent
  );

}



/* ============================================================
   37. RESET PASSWORD BUTTON
   ============================================================ */

async function handleResetPasswordButton() {

  if (!editingStudent) {

    showMessage(
      "Marka hore dooro student.",
      "warning"
    );

    return;
  }


  await resetStudentPassword(
    editingStudent
  );

}



/* ============================================================
   38. NEW STUDENT
   ============================================================ */

function startNewStudent() {

  resetStudentForm();


  if (institutionSelect) {
    institutionSelect.focus();
  }


  window.scrollTo({
    top: 0,
    behavior: "smooth"
  });

}



/* ============================================================
   39. EVENT LISTENERS
   ============================================================ */

function setupEventListeners() {


  if (studentForm) {

    studentForm.addEventListener(
      "submit",
      saveStudent
    );

  }


  if (resetFormButton) {

    resetFormButton.addEventListener(
      "click",
      resetStudentForm
    );

  }


  if (addStudentButton) {

    addStudentButton.addEventListener(
      "click",
      startNewStudent
    );

  }


  if (refreshStudentsButton) {

    refreshStudentsButton.addEventListener(
      "click",
      async () => {

        try {

          hideMessage();

          await loadStudents();

          showMessage(
            "Student records refreshed.",
            "success"
          );

        }
        catch (error) {

          showMessage(
            error?.message ||
            "Refresh failed.",
            "error"
          );

        }

      }
    );

  }


  if (searchInput) {

    searchInput.addEventListener(
      "input",
      applyFiltersAndRender
    );

  }


  if (statusFilter) {

    statusFilter.addEventListener(
      "change",
      applyFiltersAndRender
    );

  }


  if (photoInput) {

    photoInput.addEventListener(
      "change",
      handlePhotoPreview
    );

  }


  if (studentsTableBody) {

    studentsTableBody.addEventListener(
      "click",
      handleTableAction
    );

  }


  if (createAccountButton) {

    createAccountButton.addEventListener(
      "click",
      handleCreateAccountButton
    );

  }


  if (resetPasswordButton) {

    resetPasswordButton.addEventListener(
      "click",
      handleResetPasswordButton
    );

  }


  if (closeProfileModal) {

    closeProfileModal.addEventListener(
      "click",
      closeProfileModalFn
    );

  }


  if (profileModal) {

    profileModal.addEventListener(
      "click",
      event => {

        if (
          event.target ===
          profileModal
        ) {

          closeProfileModalFn();

        }

      }
    );

  }


  document.addEventListener(
    "keydown",
    event => {

      if (
        event.key ===
        "Escape"
      ) {

        closeProfileModalFn();

      }

    }
  );

}



/* ============================================================
   40. INITIALIZATION
   ============================================================ */

async function initializeStudentsPage() {

  try {

    console.log(
      "GAAWOW Students V5.5 initializing..."
    );


    ensureSupabase();


    await checkSuperAdmin();


    await loadInstitutions();


    resetStudentForm();


    await loadStudents();


    setupEventListeners();


    console.log(
      "GAAWOW Students V5.5 ready."
    );


  }
  catch (error) {

    console.error(
      "Students page initialization error:",
      error
    );


    showMessage(
      error?.message ||
      "Students page initialization failed.",
      "error"
    );

  }

}



/* ============================================================
   41. GLOBAL API
   ============================================================ */

window.GAAWOWStudents = {

  reload:
    loadStudents,

  resetForm:
    resetStudentForm,

  newStudent:
    startNewStudent,

  getStudents:
    () =>
      [...students],

  getFilteredStudents:
    () =>
      [...filteredStudents]

};



/* ============================================================
   42. START
   ============================================================ */

if (
  document.readyState ===
  "loading"
) {

  document.addEventListener(
    "DOMContentLoaded",
    initializeStudentsPage
  );

}
else {

  initializeStudentsPage();

}
