async function createStudent(data, photoFile) {

  const studentDbId = createUUID();

  const insertData = {
    id: studentDbId,

    institution_id: data.institution_id,

    full_name: data.full_name,

    gender: data.gender,

    date_of_birth: data.date_of_birth,

    phone: data.phone,

    email: data.email,

    address: data.address,

    admission_date:
      data.admission_date || getTodayDate(),

    status: data.status
  };

  const {
    data: createdStudent,
    error
  } = await withTimeout(
    supabaseClient
      .from("students")
      .insert(insertData)
      .select(`
        id,
        student_id,
        email,
        full_name,
        institution_id
      `)
      .single()
  );

  if (error) {
    throw error;
  }

  if (!createdStudent) {
    throw new Error(
      "Student was saved, but the generated Student ID could not be read."
    );
  }

  if (!createdStudent.student_id) {
    throw new Error(
      "Student ID was not generated by Supabase. " +
      "Please verify the Student ID database trigger."
    );
  }


  /* =========================================================
     CREATE STUDENT ACCOUNT
     ========================================================= */

  let accountResult = {
    accountCreated: false,
    accountNotice: null,
    loginEmail: null,
    temporaryPassword: null
  };

  if (createdStudent.email) {

    try {

      setProgress(
        10,
        "Creating student account..."
      );

      const {
        data: accountData,
        error: accountError
      } =
        await supabaseClient.functions.invoke(
          "create-student-account",
          {
            body: {
              student_db_id:
                createdStudent.id,

              student_id:
                createdStudent.student_id,

              full_name:
                createdStudent.full_name,

              email:
                createdStudent.email,

              institution_id:
                createdStudent.institution_id
            }
          }
        );

      if (accountError) {
        throw accountError;
      }

      if (
        !accountData ||
        !accountData.success
      ) {
        throw new Error(
          accountData?.message ||
          "Student account could not be created."
        );
      }

      accountResult = {
        accountCreated: true,

        accountNotice:
          "Student login account created successfully.",

        loginEmail:
          accountData.email ||
          createdStudent.email,

        temporaryPassword:
          accountData.temporary_password ||
          null
      };

    } catch (accountError) {

      console.error(
        "Student account creation error:",
        accountError
      );

      accountResult = {
        accountCreated: false,

        accountNotice:
          "Student was saved, but the login account could not be created: " +
          getErrorMessage(accountError),

        loginEmail:
          createdStudent.email,

        temporaryPassword:
          null
      };
    }
  }


  /* =========================================================
     PHOTO
     ========================================================= */

  let result = {
    photoError: null,
    photoNotice: null
  };

  if (photoFile) {

    try {

      result =
        await savePhotoForStudent(
          createdStudent.id,
          photoFile
        );

    } catch (photoErr) {

      console.error(
        "Photo upload error:",
        photoErr
      );

      result = {
        photoError:
          getErrorMessage(photoErr),

        photoNotice: null
      };
    }
  }


  return {

    studentDbId:
      createdStudent.id,

    generatedStudentId:
      createdStudent.student_id,

    ...result,

    ...accountResult
  };
}
